services:
  epr-packaging-frontend:
    build:
      context: .
      dockerfile: ./compose/epr-packaging-frontend/Dockerfile.timeshift
      args:
        BASE_IMAGE: devrwdinfac1401.azurecr.io/eprpackagingfrontendrepository:${EPR_PACKAGING_FRONTEND:-main-latest}
    image: epr-packaging-frontend:timeshift
    command: ["sh", "-c", "echo 'Setting fake time to March 1, 2026' && faketime -f '2026-03-01 12:00:00' /bin/date && echo 'Starting application...' && exec faketime --exclude-monotonic -f '2026-03-01 12:00:00' dotnet FrontendSchemeRegistration.UI.dll"]
    profiles:
      - timeshift

volumes:
  azurite-data:
  sqledge-data:
  token-cache:
